### ISSUE TITLE
ResNet18: incompatible architecture and pretrained parameters

### ISSUE THREAD

**Issue by andreuvall** [LuxDL/Boltz.jl#18]
ResNets are transformed into Lux from Metalhead using the [`resnet`](https://github.com/LuxDL/Boltz.jl/blob/9088c3f6cffead5a64fbaeddb1eb834dac437c5c/ext/BoltzMetalheadExt.jl#L19-L34) function. `transform` is yielding a `Chain` with two `Chain`s in it, each containing a number of layers. We can also see this if we use `Lux.setup` on the model.
```
using Metalhead
using Lux
using Random

model = transform(ResNet(18).layers);
ps, st = Lux.setup(Random.default_rng(), model);
@show keys(ps)
> keys(ps) = (:layer_1, :layer_2)
```
There is the option to pass `pretrained = true` to the `resnet` function. However, the pretrained parameters loaded by [`_initialize_model`](https://github.com/LuxDL/Boltz.jl/blob/9088c3f6cffead5a64fbaeddb1eb834dac437c5c/src/utils.jl#L44) are a "flattened" named tuple of 14 layers.
```
using Boltz

_, ps_prime, st_prime = resnet(:resnet18; pretrained = true);
@show keys(ps_prime)
> keys(ps_prime) = (:layer_1, :layer_2, :layer_3, :layer_4, :layer_5, :layer_6, :layer_7, :layer_8, :layer_9, :layer_10, :layer_11, :layer_12, :layer_13, :layer_14)
```
Therefore, the model architecture and the pretrained parameters are not compatible.
```
x = randn(Float32, 224, 224, 3, 1);
model(x, ps, st)  # this works
model(x, ps_prime, st_prime)  # but this doesn't
```

**Comment by avik-pal** [comment]
I see that is the problem. The initial weights were imported in Lux 0.4, and since some defaults changed it led to this breakage.

> Here I only checked that two of the pretrained parameter arrays are equal. I am also unsure of the effects of the state being ignored when loading the model and the pretrained parameters.

States not being preserved means that your predictions won't be correct. Specify `force_preserve` (https://lux.csail.mit.edu/dev/api/Lux/flux_to_lux#Lux.transform) and that should do it for now
